FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Jobbplanapi

Api beskrivelse for jobbplan

## VaktApi Collection [/api/VaktApi/{id}]

### Se alle vakter for prosjektId[GET]

+ Response 200 (application/json)

        [
            {
                "Beskrivelse":null,
                "Brukernavn":"mats_loekken@hotmail.com",
                "Ledig":false,
                "VaktId":1,
                "color":"#3A87AD",
                "end":"2016-03-15T14:50:00",
                "start":"2016-03-15T09:44:00",
                "title":"Dagvakt: Mats Løkken"
            },
            {
                "Beskrivelse":null,
                "Brukernavn":"mats_loekken@hotmail.com",
                "Ledig":false,
                "VaktId":1,
                "color":"#3A87AD",
                "end":"2016-03-15T14:50:00",
                "start":"2016-03-15T09:44:00",
                "title":"Dagvakt: Atle Aspelien"
            }
        ]


### Ta ledig vakt [PUT]

+ Request (application/json)
           
           PUT /api/VaktApi/15
        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/VaktApi/15
            
    + Body
    
+ Response 404 (text/plain)

        Kunne ikke ta vakt!
        

### Slett vakt [DELETE]

+ Request (application/json)

            DELETE /api/VaktApi/15

+ Response 201 (application/json)

    + Headers
    
            Location: /api/VaktApi/15
            
    + Body
            
+ Response 404 (text/plain)

        Kunne ikke slette vakt!

## VaktApi Collection [/api/VaktApi/]

### Se alle vakter for bruker[GET]

+ Response 200 (application/json)

        [
            {
                "Beskrivelse":null,
                "Brukernavn":"mats_loekken@hotmail.com",
                "Ledig":false,
                "VaktId":1,
                "color":"#3A87AD",
                "end":"2016-03-15T14:50:00",
                "start":"2016-03-15T09:44:00",
                "title":"Dagvakt: Mats Løkken"
            },
            {
                "Beskrivelse":null,
                "Brukernavn":"mats_loekken@hotmail.com",
                "Ledig":false,
                "VaktId":1,
                "color":"#3A87AD",
                "end":"2016-03-15T14:50:00",
                "start":"2016-03-15T09:44:00",
                "title":"Dagvakt: Mats Løkken"
            }
        ]

### Legg til en ny vakt [POST]

+ Request (application/json)
           
            {
                "start":"05.05.2016",
                "startTid":"12:36",
                "endTid":"17:36",
                "end":"06.05.2016",
                "title":"Dagvakt",
                "Beskrivelse":"",
                "ProsjektId":"7",
                "BrukerId":"8",
                "endDato":true
            }
        

+ Response 201 (application/json)

    + Headers
    
            Cache-Control: no-cache
            Pragma: no-cache
            Content-Length: 166
            Expires: -1
            Location: http://jobbplan2016.azurewebsites.net/api/VaktApi/0
            Server: Microsoft-IIS/8.0
            X-AspNet-Version: 4.0.30319
            X-Powered-By: ASP.NET
            Date: Tue, 03 May 2016 10:39:08 GMT

    + Body
    
            {  
                "Vaktid":0,
                "start":"05.05.2016",
                "startTid":"12:36",
                "endTid":"17:36",
                "endDato":true,
                "end":"06.05.2016",
                "title":"Dagvakt",
                "Beskrivelse":"",
                "BrukerId":8,
                "ProsjektId":7
            }
            
+ Response 404 (text/plain)

        Kunne ikke sette inn databasen
        


## VaktApi2 Collection [/api/VaktApi2/]

### Endre vakt [PUT]

+ Request (application/json)
           
           {
                "VaktId":"14",
                "start":"05.05.2016",
                "startTid":"16:57",
                "end":"",
                "endTid":"20:57",
                "title":"",
                "Beskrivelse":"",
                "ProsjektId":"7",
                "BrukerId":"0",
                "endDato":false
            }
        

+ Response 201 (application/json)

    + Headers
    
            
    + Body
    
            {   
                "Vaktid":14,
                "start":"05.05.2016",
                "startTid":"16:57",
                "endTid":"20:57",
                "endDato":false,
                "end":"",
                "title":"",
                "Beskrivelse":"",
                "BrukerId":0,
                "ProsjektId":7
            }
                
+ Response 404 (text/plain)

        Kunne ikke ta vakt!
        
## BrukerApi Collection [/api/BrukerApi/{id}]

### Hent alle brukere [GET]


+ Request (application/json)
           
        GET /api/BrukerApi/7 HTTP/1.1

        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/BrukerApi/
            
            
    + Body
    
             [
                {
                    "ProsjektId":0,
                    "ProsjektDeltakerId":7,
                    "Navn":"Gordo løkken",
                    "Brukernavn":"gordo@hotmail.com",
                    "BrukerId":3,
                    "Admin":false
                },
                {
                    "ProsjektId":0,
                    "ProsjektDeltakerId":8,
                    "Navn":"Mats Løkken",
                    "Brukernavn":"mats_loekken@hotmail.com",
                    "BrukerId":1,
                    "Admin":true
                }
            ]
            
+ Response 404 (text/plain)

        Kunne ikke oprette bruker!


## BrukerApi Collection [/api/BrukerApi]

### Legg til en ny bruker [POST]

+ Request (application/json)
           
            {
                "Fornavn":"testing",
                "Etternavn":"testing",
                "Telefonnummer":"12312312",
                "Email":"testing@testing.com",
                "BekreftPassord":"123123123"
            }
        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/BrukerApi/
            
            
    + Body
    
             {
                "Fornavn":"testing",
                "Etternavn":"testing",
                "Telefonnummer":"12312312",
                "Email":"testing@testing.com",
                "BekreftPassord":"123123123"
            }
            
+ Response 404 (text/plain)

        Kunne ikke oprette bruker!


## ProsjektApi Collection [/api/ProsjektApi/]

### Se alle prosjekter [GET]

+ Request (application/json)
           
            GET /api/ProsjektApi/

+ Response 200 (application/json)

        [
            {
                "Id":7,
                "Arbeidsplass":"TestButikk"
            },
            {   
                "Id":9,
                "Arbeidsplass":"Beste jobben"
            },
            {
                "Id":10,"Arbeidsplass":"testets"
            }
        ]


### Legg til en ny bruker [POST]

+ Request (application/json)
           
            {
                "Fornavn":"testing",
                "Etternavn":"testing",
                "Telefonnummer":"12312312",
                "Email":"testing@testing.com",
                "BekreftPassord":"123123123"
            }
        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/BrukerApi/
            
            
    + Body
    
             {
                "Fornavn":"testing",
                "Etternavn":"testing",
                "Telefonnummer":"12312312",
                "Email":"testing@testing.com",
                "BekreftPassord":"123123123"
            }
            
+ Response 404 (text/plain)

        Kunne ikke oprette bruker!

## ProsjektDeltakelseApi Collection [/api/ProsjektDeltakelseApi/{id}]

### Er Admin [GET]

+ Request (application/json)
           
            GET /api/ProsjektDeltakelseApi/7 HTTP/1.1


+ Response 200 (application/json)

                true

## ProsjektDeltakelseApi Collection [/api/ProsjektDeltakelseApi]

### Registrer Prosjektdeltakelse [POST]


+ Request (application/json)
           
            {
                "ProsjektId":"15"
            }
        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/BrukerApi/
            
            
    + Body
    
             {
                "MeldingId":0,
                "Tid":"0001-01-01T00:00:00",
                "ProsjektId":15,
                "TilBruker":null,
                "FraBruker":null,
                "Prosjektnavn":null,
                "Melding":null
            }
            
+ Response 404 (text/plain)

        Kunne ikke oprette bruker!
        

## Sjef Collection [/api/Sjef]

### Gi bruker Admintilgang [POST]

+ Request (application/json)
        
            {
                "BrukerId":"8",
                "ProsjektId":"7"
            }

+ Response 201 (application/json)

    + Headers
    
            Location: /api/Sjef/

    + Body
    
            {
                "BrukerId":8,
                "ProsjektId":7,
                "Tittel":null
            }

### FjernAdminTilgang [PUT]

+ Request (application/json)
           
        {
            "BrukerId":"8",
            "ProsjektId":"7"
        }

+ Response 201 (application/json)

    + Headers
    
            Location: /api/VaktApi/15
            
    + Body
    
+ Response 404 (text/plain)

        Kunne ikke ta vakt!