FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Jobbplanapi

Api beskrivelse for jobbplan

## Maler Collection [/api/Maler/{id}]

### Se alle maler for prosjekt[GET]

+ Response 200 (application/json)

        [
            {
                "ProsjektId":0,
                "Tittel":"d1",
                "startTid":"17:39",
                "sluttTid":"21:39"
            }
        ]
        
## Maler Collection [/api/Maler/]

### Legg til en ny mal [POST]

+ Request (application/json)
           
            {   
                "startTid":"17:39",
                "sluttTid":"21:39",
                "Tittel":"d1",
                "ProsjektId":"7"
            }
        

+ Response 201 (application/json)

    + Headers
    
            Expires: -1
            Location: http://jobbplan2016.azurewebsites.net/api/Maler


    + Body
    
            {
                "Tittel":"d1",
                "startTid":"17:39",
                "sluttTid":"21:39",
                "ProsjektId":7
            }
            
+ Response 404 (text/plain)

        Kunne ikke sette inn databasen
        




## VaktApi Collection [/api/VaktApi/{id}]

### Se alle vakter for prosjektId[GET]

+ Response 200 (application/json)

        [
            {
                "Beskrivelse":null,
                "Brukernavn":"mats_loekken@hotmail.com",
                "Ledig":false,
                "VaktId":1,
                "color":"#3A87AD",
                "end":"2016-03-15T14:50:00",
                "start":"2016-03-15T09:44:00",
                "title":"Dagvakt: Mats Løkken"
            },
            {
                "Beskrivelse":null,
                "Brukernavn":"mats_loekken@hotmail.com",
                "Ledig":false,
                "VaktId":1,
                "color":"#3A87AD",
                "end":"2016-03-15T14:50:00",
                "start":"2016-03-15T09:44:00",
                "title":"Dagvakt: Atle Aspelien"
            }
        ]


### Ta ledig vakt [PUT]

+ Request (application/json)
           
           PUT /api/VaktApi/15
        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/VaktApi/15
            
    + Body
    
+ Response 404 (text/plain)

        Kunne ikke ta vakt!
        

### Slett vakt [DELETE]

+ Request (application/json)

            DELETE /api/VaktApi/15

+ Response 201 (application/json)

    + Headers
    
            Location: /api/VaktApi/15
            
    + Body
            
+ Response 404 (text/plain)

        Kunne ikke slette vakt!

## VaktApi Collection [/api/VaktApi/]

### Se alle vakter for bruker[GET]

+ Response 200 (application/json)

        [
            {
                "Beskrivelse":null,
                "Brukernavn":"mats_loekken@hotmail.com",
                "Ledig":false,
                "VaktId":1,
                "color":"#3A87AD",
                "end":"2016-03-15T14:50:00",
                "start":"2016-03-15T09:44:00",
                "title":"Dagvakt: Mats Løkken"
            },
            {
                "Beskrivelse":null,
                "Brukernavn":"mats_loekken@hotmail.com",
                "Ledig":false,
                "VaktId":1,
                "color":"#3A87AD",
                "end":"2016-03-15T14:50:00",
                "start":"2016-03-15T09:44:00",
                "title":"Dagvakt: Mats Løkken"
            }
        ]

### Legg til en ny vakt [POST]

+ Request (application/json)
           
            {
                "start":"05.05.2016",
                "startTid":"12:36",
                "endTid":"17:36",
                "end":"06.05.2016",
                "title":"Dagvakt",
                "Beskrivelse":"",
                "ProsjektId":"7",
                "BrukerId":"8",
                "endDato":true
            }
        

+ Response 201 (application/json)

    + Headers
    
            Cache-Control: no-cache
            Pragma: no-cache
            Content-Length: 166
            Expires: -1
            Location: http://jobbplan2016.azurewebsites.net/api/VaktApi/0
            Server: Microsoft-IIS/8.0
            X-AspNet-Version: 4.0.30319
            X-Powered-By: ASP.NET
            Date: Tue, 03 May 2016 10:39:08 GMT

    + Body
    
            {  
                "Vaktid":0,
                "start":"05.05.2016",
                "startTid":"12:36",
                "endTid":"17:36",
                "endDato":true,
                "end":"06.05.2016",
                "title":"Dagvakt",
                "Beskrivelse":"",
                "BrukerId":8,
                "ProsjektId":7
            }
            
+ Response 404 (text/plain)

        Kunne ikke sette inn databasen
        


## VaktApi2 Collection [/api/VaktApi2/]

### Endre vakt [PUT]

+ Request (application/json)
           
           {
                "VaktId":"14",
                "start":"05.05.2016",
                "startTid":"16:57",
                "end":"",
                "endTid":"20:57",
                "title":"",
                "Beskrivelse":"",
                "ProsjektId":"7",
                "BrukerId":"0",
                "endDato":false
            }
        

+ Response 201 (application/json)

    + Headers
    
            
    + Body
    
            {   
                "Vaktid":14,
                "start":"05.05.2016",
                "startTid":"16:57",
                "endTid":"20:57",
                "endDato":false,
                "end":"",
                "title":"",
                "Beskrivelse":"",
                "BrukerId":0,
                "ProsjektId":7
            }
                
+ Response 404 (text/plain)

        Kunne ikke ta vakt!
        
## BrukerApi Collection [/api/BrukerApi/{id}]

### Hent alle brukere [GET]


+ Request (application/json)
           
        GET /api/BrukerApi/7 HTTP/1.1

        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/BrukerApi/
            
            
    + Body
    
             [
                {
                    "ProsjektId":0,
                    "ProsjektDeltakerId":7,
                    "Navn":"Gordo løkken",
                    "Brukernavn":"gordo@hotmail.com",
                    "BrukerId":3,
                    "Admin":false
                },
                {
                    "ProsjektId":0,
                    "ProsjektDeltakerId":8,
                    "Navn":"Mats Løkken",
                    "Brukernavn":"mats_loekken@hotmail.com",
                    "BrukerId":1,
                    "Admin":true
                }
            ]
            
+ Response 404 (text/plain)

        Kunne ikke oprette bruker!


## BrukerApi Collection [/api/BrukerApi]

### Legg til en ny bruker [POST]

+ Request (application/json)
           
            {
                "Fornavn":"testing",
                "Etternavn":"testing",
                "Telefonnummer":"12312312",
                "Email":"testing@testing.com",
                "BekreftPassord":"123123123"
            }
        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/BrukerApi/
            
            
    + Body
    
             {
                "Fornavn":"testing",
                "Etternavn":"testing",
                "Telefonnummer":"12312312",
                "Email":"testing@testing.com",
                "BekreftPassord":"123123123"
            }
            
+ Response 404 (text/plain)

        Kunne ikke oprette bruker!


## ProsjektApi Collection [/api/ProsjektApi/]

### Se alle prosjekter [GET]

+ Request (application/json)
           
            GET /api/ProsjektApi/

+ Response 200 (application/json)

        [
            {
                "Id":7,
                "Arbeidsplass":"TestButikk"
            },
            {   
                "Id":9,
                "Arbeidsplass":"Beste jobben"
            },
            {
                "Id":10,"Arbeidsplass":"testets"
            }
        ]

+ Response 404 (text/plain)

        Kunne ikke hente prosjekter

### Legg til en ny bruker [POST]

+ Request (application/json)
           
            {
                "Fornavn":"testing",
                "Etternavn":"testing",
                "Telefonnummer":"12312312",
                "Email":"testing@testing.com",
                "BekreftPassord":"123123123"
            }
        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/BrukerApi/
            
            
    + Body
    
             {
                "Fornavn":"testing",
                "Etternavn":"testing",
                "Telefonnummer":"12312312",
                "Email":"testing@testing.com",
                "BekreftPassord":"123123123"
            }
            
+ Response 404 (text/plain)

        Kunne ikke oprette bruker!
        
## ProsjektApi Collection [/api/ProsjektApi/{id}]

### Slett Prosjekt [DELETE]

+ Request (application/json)

            DELETE /api/ProsjektApi/18 

+ Response 200 (application/json)

    + Headers
    
            
    + Body
            
+ Response 404 (text/plain)

        Kunne ikke slette prosjekt

## ProsjektDeltakelseApi Collection [/api/ProsjektDeltakelseApi/{id}]

### Er Admin [GET]

+ Request (application/json)
           
            GET /api/ProsjektDeltakelseApi/7 HTTP/1.1


+ Response 200 (application/json)

                true

## ProsjektDeltakelseApi Collection [/api/ProsjektDeltakelseApi]

### Registrer Prosjektdeltakelse [POST]


+ Request (application/json)
           
            {
                "ProsjektId":"15"
            }
        

+ Response 201 (application/json)

    + Headers
    
            Location: /api/BrukerApi/
            
            
    + Body
    
             {
                "MeldingId":0,
                "Tid":"0001-01-01T00:00:00",
                "ProsjektId":15,
                "TilBruker":null,
                "FraBruker":null,
                "Prosjektnavn":null,
                "Melding":null
            }
            
+ Response 404 (text/plain)

        Kunne ikke oprette bruker!
        
## Sjef Collection [/api/Sjef/{id}]

### SlettRequestSomAdmin [DELETE]

+ Request (application/json)
        
            DELETE /api/Sjef/10 HTTP/1.1


+ Response 201 (application/json)


## Sjef Collection [/api/Sjef]

### Gi bruker Admintilgang [POST]

+ Request (application/json)
        
            {
                "BrukerId":"8",
                "ProsjektId":"7"
            }

+ Response 201 (application/json)

    + Headers
    
            Location: /api/Sjef/

    + Body
    
            {
                "BrukerId":8,
                "ProsjektId":7,
                "Tittel":null
            }

### FjernAdminTilgang [PUT]

+ Request (application/json)
           
        {
            "BrukerId":"8",
            "ProsjektId":"7"
        }

+ Response 201 (application/json)


## ProsjektReq Collection [/api/ProsjektreqApi/{id}]

### VisRequesterForProsjekt [GET]

+ Request (application/json)
           
            GET /api/ProsjektreqApi/7 HTTP/1.1


+ Response 200 (application/json)

        [
            {
                "MeldingId":10,
                "Tid":"2016-05-12T09:23:03.57",
                "ProsjektId":0,
                "TilBruker":"gordo@hotmail.com",
                "FraBruker":null,
                "Prosjektnavn":null,
                "Melding":null
            }
        ]

### SlettRequest [DELETE]

+ Request (application/json)
           
        {
            "BrukerId":"8",
            "ProsjektId":"7"
        }

+ Response 201 (application/json)

## ProsjektReq Collection [/api/ProsjektreqApi]

### VisRequester [GET]

+ Request (application/json)
           
            GET /api/ProsjektreqApi HTTP/1.1


+ Response 200 (application/json)

        [
            {
                "MeldingId":0,
                "Tid":"2016-05-10T09:22:01.337",
                "ProsjektId":17,
                "TilBruker":"mats_loekken@hotmail.com",
                "FraBruker":"sofie_ao@hotmail.com",
                "Prosjektnavn":"Prosjektet",
                "Melding":" har invitert deg til å bli medlem av: "
            }
        ]


### LeggTilBrukerRequest [POST]

+ Request (application/json)
        
           {
                "TilBruker":"gordo@hotmail.com",
                "ProsjektId":"7"
            }

+ Response 201 (application/json)

    + Headers
    
            Location: /api/ProsjektreqApi

    + Body
    
            {
                "TilBruker":"gordo@hotmail.com",
                "ProsjektId":7
            }
            
            
            
## Timeliste Collection [/api/TimelisteApi/{id}]

### Se timeliste for prosjekt[GET]

+ Response 200 (application/json)

        [
            {
                "BrukerId":0,
                "Timer":0.0,
                "Fornavn":null,
                "Etternavn":null,
                "PeriodeStart":"2016-05-05T16:57:00",
                "PeriodeSlutt":"2016-05-05T20:57:00",
                "Sum":0.0,
                "ProsjektId":0
            },
            {
                "BrukerId":0,
                "Timer":0.0,
                "Fornavn":null,
                "Etternavn":null,
                "PeriodeStart":"2016-05-05T23:19:00",
                "PeriodeSlutt":"2016-05-05T23:23:00",
                "Sum":0.0,
                "ProsjektId":0
            },
            {
                "BrukerId":0,
                "Timer":0.0,
                "Fornavn":null,
                "Etternavn":null,
                "PeriodeStart":"2016-05-11T09:49:00",
                "PeriodeSlutt":"2016-05-11T19:49:00",
                "Sum":0.0,
                "ProsjektId":0
            }
        ]